--
-- PostgreSQL database dump
--

\restrict cPG2bBeddoTrLIVe7IqDOhb5rk5GNoDfhC1wwfprKExiUZtfkGBCnTFbmeaP3v7

-- Dumped from database version 16.10
-- Dumped by pg_dump version 16.10

-- Started on 2025-10-28 18:39:01

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 24861)
-- Name: RoleClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."RoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."RoleClaims" OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 24860)
-- Name: RoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."RoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."RoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 24846)
-- Name: Roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Roles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE public."Roles" OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 24874)
-- Name: UserClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."UserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."UserClaims" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 24873)
-- Name: UserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."UserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 24886)
-- Name: UserLogins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."UserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


ALTER TABLE public."UserLogins" OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 24898)
-- Name: UserRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."UserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


ALTER TABLE public."UserRoles" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 24915)
-- Name: UserTokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."UserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


ALTER TABLE public."UserTokens" OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 24853)
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" text NOT NULL,
    "Documentos" text,
    "UserName" character varying(150),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    "DocumentNumber" text,
    "FullName" text
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 24841)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 24939)
-- Name: neuro_com_hab; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.neuro_com_hab (
    neuro_cod_grp character varying(6) NOT NULL,
    neuro_cod_comp integer NOT NULL,
    neuro_des_comp character varying(60) NOT NULL,
    neuro_seq_comp integer NOT NULL
);


ALTER TABLE public.neuro_com_hab OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 25116)
-- Name: neuro_default_answers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.neuro_default_answers (
    id integer NOT NULL,
    form_id integer NOT NULL,
    label character varying(100) NOT NULL,
    color character varying(20) NOT NULL
);


ALTER TABLE public.neuro_default_answers OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 25115)
-- Name: neuro_default_answers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.neuro_default_answers_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.neuro_default_answers_id_seq OWNER TO postgres;

--
-- TOC entry 4891 (class 0 OID 0)
-- Dependencies: 236
-- Name: neuro_default_answers_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.neuro_default_answers_id_seq OWNED BY public.neuro_default_answers.id;


--
-- TOC entry 229 (class 1259 OID 25021)
-- Name: neuro_form; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.neuro_form (
    form_id integer NOT NULL,
    form_name character varying(120) NOT NULL,
    form_desc character varying(255),
    form_status integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone
);


ALTER TABLE public.neuro_form OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 25020)
-- Name: neuro_form_form_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.neuro_form ALTER COLUMN form_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.neuro_form_form_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 25045)
-- Name: neuro_form_question; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.neuro_form_question (
    question_id integer NOT NULL,
    section_id integer NOT NULL,
    question_text character varying(255) NOT NULL,
    neuro_cod_comp integer,
    observations character varying(255),
    seq_order integer NOT NULL
);


ALTER TABLE public.neuro_form_question OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 25044)
-- Name: neuro_form_question_question_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.neuro_form_question ALTER COLUMN question_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.neuro_form_question_question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 25063)
-- Name: neuro_form_response; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.neuro_form_response (
    response_id integer NOT NULL,
    form_id integer NOT NULL,
    user_id character varying(50) NOT NULL,
    question_id integer NOT NULL,
    degree_code integer NOT NULL,
    observacao character varying(255),
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.neuro_form_response OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 25062)
-- Name: neuro_form_response_response_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.neuro_form_response ALTER COLUMN response_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.neuro_form_response_response_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 25029)
-- Name: neuro_form_section; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.neuro_form_section (
    section_id integer NOT NULL,
    form_id integer NOT NULL,
    sec_name character varying(120) NOT NULL,
    neuro_cod_grp character varying(6),
    seq_order integer NOT NULL
);


ALTER TABLE public.neuro_form_section OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 25028)
-- Name: neuro_form_section_section_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.neuro_form_section ALTER COLUMN section_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.neuro_form_section_section_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 24956)
-- Name: neuro_gra_com; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.neuro_gra_com (
    neuro_cod_grp character varying(6) NOT NULL,
    neuro_cod_gra integer NOT NULL,
    neuro_des_gra character varying(20) NOT NULL
);


ALTER TABLE public.neuro_gra_com OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 24934)
-- Name: neuro_grp_hab; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.neuro_grp_hab (
    neuro_cod_grp character varying(6) NOT NULL,
    neuro_des_grp character varying(60) NOT NULL
);


ALTER TABLE public.neuro_grp_hab OWNER TO postgres;

--
-- TOC entry 4686 (class 2604 OID 25119)
-- Name: neuro_default_answers id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.neuro_default_answers ALTER COLUMN id SET DEFAULT nextval('public.neuro_default_answers_id_seq'::regclass);


--
-- TOC entry 4698 (class 2606 OID 24867)
-- Name: RoleClaims PK_RoleClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."RoleClaims"
    ADD CONSTRAINT "PK_RoleClaims" PRIMARY KEY ("Id");


--
-- TOC entry 4690 (class 2606 OID 24852)
-- Name: Roles PK_Roles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Roles"
    ADD CONSTRAINT "PK_Roles" PRIMARY KEY ("Id");


--
-- TOC entry 4701 (class 2606 OID 24880)
-- Name: UserClaims PK_UserClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserClaims"
    ADD CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id");


--
-- TOC entry 4704 (class 2606 OID 24892)
-- Name: UserLogins PK_UserLogins; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserLogins"
    ADD CONSTRAINT "PK_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- TOC entry 4707 (class 2606 OID 24904)
-- Name: UserRoles PK_UserRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserRoles"
    ADD CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- TOC entry 4709 (class 2606 OID 24921)
-- Name: UserTokens PK_UserTokens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserTokens"
    ADD CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- TOC entry 4694 (class 2606 OID 24859)
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- TOC entry 4688 (class 2606 OID 24845)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4727 (class 2606 OID 25121)
-- Name: neuro_default_answers neuro_default_answers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.neuro_default_answers
    ADD CONSTRAINT neuro_default_answers_pkey PRIMARY KEY (id);


--
-- TOC entry 4719 (class 2606 OID 25027)
-- Name: neuro_form neuro_form_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.neuro_form
    ADD CONSTRAINT neuro_form_pkey PRIMARY KEY (form_id);


--
-- TOC entry 4723 (class 2606 OID 25051)
-- Name: neuro_form_question neuro_form_question_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.neuro_form_question
    ADD CONSTRAINT neuro_form_question_pkey PRIMARY KEY (question_id);


--
-- TOC entry 4725 (class 2606 OID 25068)
-- Name: neuro_form_response neuro_form_response_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.neuro_form_response
    ADD CONSTRAINT neuro_form_response_pkey PRIMARY KEY (response_id);


--
-- TOC entry 4721 (class 2606 OID 25033)
-- Name: neuro_form_section neuro_form_section_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.neuro_form_section
    ADD CONSTRAINT neuro_form_section_pkey PRIMARY KEY (section_id);


--
-- TOC entry 4713 (class 2606 OID 24943)
-- Name: neuro_com_hab pk_neuro_com_hab; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.neuro_com_hab
    ADD CONSTRAINT pk_neuro_com_hab PRIMARY KEY (neuro_cod_comp);


--
-- TOC entry 4717 (class 2606 OID 24960)
-- Name: neuro_gra_com pk_neuro_gra_com; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.neuro_gra_com
    ADD CONSTRAINT pk_neuro_gra_com PRIMARY KEY (neuro_cod_gra);


--
-- TOC entry 4711 (class 2606 OID 24938)
-- Name: neuro_grp_hab pk_neuro_grp_hab; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.neuro_grp_hab
    ADD CONSTRAINT pk_neuro_grp_hab PRIMARY KEY (neuro_cod_grp);


--
-- TOC entry 4715 (class 2606 OID 24945)
-- Name: neuro_com_hab uq_neuro_com_hab_grp_seq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.neuro_com_hab
    ADD CONSTRAINT uq_neuro_com_hab_grp_seq UNIQUE (neuro_cod_grp, neuro_seq_comp);


--
-- TOC entry 4692 (class 1259 OID 24932)
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "EmailIndex" ON public."Users" USING btree ("NormalizedEmail");


--
-- TOC entry 4696 (class 1259 OID 24927)
-- Name: IX_RoleClaims_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_RoleClaims_RoleId" ON public."RoleClaims" USING btree ("RoleId");


--
-- TOC entry 4699 (class 1259 OID 24929)
-- Name: IX_UserClaims_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_UserClaims_UserId" ON public."UserClaims" USING btree ("UserId");


--
-- TOC entry 4702 (class 1259 OID 24930)
-- Name: IX_UserLogins_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_UserLogins_UserId" ON public."UserLogins" USING btree ("UserId");


--
-- TOC entry 4705 (class 1259 OID 24931)
-- Name: IX_UserRoles_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_UserRoles_RoleId" ON public."UserRoles" USING btree ("RoleId");


--
-- TOC entry 4691 (class 1259 OID 24928)
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."Roles" USING btree ("NormalizedName");


--
-- TOC entry 4695 (class 1259 OID 24933)
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."Users" USING btree ("NormalizedUserName");


--
-- TOC entry 4728 (class 2606 OID 24868)
-- Name: RoleClaims FK_RoleClaims_Roles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."RoleClaims"
    ADD CONSTRAINT "FK_RoleClaims_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."Roles"("Id") ON DELETE CASCADE;


--
-- TOC entry 4729 (class 2606 OID 24881)
-- Name: UserClaims FK_UserClaims_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserClaims"
    ADD CONSTRAINT "FK_UserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 4730 (class 2606 OID 24893)
-- Name: UserLogins FK_UserLogins_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserLogins"
    ADD CONSTRAINT "FK_UserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 4731 (class 2606 OID 24905)
-- Name: UserRoles FK_UserRoles_Roles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserRoles"
    ADD CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."Roles"("Id") ON DELETE CASCADE;


--
-- TOC entry 4732 (class 2606 OID 24910)
-- Name: UserRoles FK_UserRoles_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserRoles"
    ADD CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 4733 (class 2606 OID 24922)
-- Name: UserTokens FK_UserTokens_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserTokens"
    ADD CONSTRAINT "FK_UserTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- TOC entry 4737 (class 2606 OID 25057)
-- Name: neuro_form_question fk_form_question_comp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.neuro_form_question
    ADD CONSTRAINT fk_form_question_comp FOREIGN KEY (neuro_cod_comp) REFERENCES public.neuro_com_hab(neuro_cod_comp) ON DELETE SET NULL;


--
-- TOC entry 4739 (class 2606 OID 25069)
-- Name: neuro_form_response fk_form_response_form; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.neuro_form_response
    ADD CONSTRAINT fk_form_response_form FOREIGN KEY (form_id) REFERENCES public.neuro_form(form_id) ON DELETE CASCADE;


--
-- TOC entry 4735 (class 2606 OID 25034)
-- Name: neuro_form_section fk_form_section_form; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.neuro_form_section
    ADD CONSTRAINT fk_form_section_form FOREIGN KEY (form_id) REFERENCES public.neuro_form(form_id) ON DELETE CASCADE;


--
-- TOC entry 4736 (class 2606 OID 25039)
-- Name: neuro_form_section fk_form_section_grp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.neuro_form_section
    ADD CONSTRAINT fk_form_section_grp FOREIGN KEY (neuro_cod_grp) REFERENCES public.neuro_grp_hab(neuro_cod_grp) ON DELETE SET NULL;


--
-- TOC entry 4734 (class 2606 OID 24946)
-- Name: neuro_com_hab fk_neuro_com_hab_grp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.neuro_com_hab
    ADD CONSTRAINT fk_neuro_com_hab_grp FOREIGN KEY (neuro_cod_grp) REFERENCES public.neuro_grp_hab(neuro_cod_grp) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 4740 (class 2606 OID 25074)
-- Name: neuro_form_response fk_question_response; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.neuro_form_response
    ADD CONSTRAINT fk_question_response FOREIGN KEY (question_id) REFERENCES public.neuro_form_question(question_id) ON DELETE CASCADE;


--
-- TOC entry 4741 (class 2606 OID 25079)
-- Name: neuro_form_response fk_response_degree; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.neuro_form_response
    ADD CONSTRAINT fk_response_degree FOREIGN KEY (degree_code) REFERENCES public.neuro_gra_com(neuro_cod_gra) ON DELETE RESTRICT;


--
-- TOC entry 4738 (class 2606 OID 25052)
-- Name: neuro_form_question fk_section_question; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.neuro_form_question
    ADD CONSTRAINT fk_section_question FOREIGN KEY (section_id) REFERENCES public.neuro_form_section(section_id) ON DELETE CASCADE;


--
-- TOC entry 4742 (class 2606 OID 25122)
-- Name: neuro_default_answers neuro_default_answers_form_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.neuro_default_answers
    ADD CONSTRAINT neuro_default_answers_form_id_fkey FOREIGN KEY (form_id) REFERENCES public.neuro_form(form_id) ON DELETE CASCADE;


-- Completed on 2025-10-28 18:39:02

--
-- PostgreSQL database dump complete
--

\unrestrict cPG2bBeddoTrLIVe7IqDOhb5rk5GNoDfhC1wwfprKExiUZtfkGBCnTFbmeaP3v7

